"""
models.py — Core data models for the Advanced Context Intelligence Engine
نماذج البيانات الأساسية لمحرك ذكاء السياق المتقدم
"""

from __future__ import annotations

import time
import hashlib
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple


# ─────────────────────────────────────────────────────────────────────────────
#  Enumerations
# ─────────────────────────────────────────────────────────────────────────────

class QueryIntent(Enum):
    """type of user query intent — guides retrieval and response generation"""
    FACTUAL      = "factual"       # ما / من / متى → إجابة مباشرة
    REASONING    = "reasoning"     # لماذا / كيف  → تحليل عميق
    COMPARATIVE  = "comparative"   # قارن / الفرق  → مقارنة
    PROCEDURAL   = "procedural"    # خطوات / كيفية → إجراء
    CODE         = "code"          # كود / برمجة   → كود برمجي
    SUMMARIZE    = "summarize"     # ملخص / اشرح   → تلخيص
    UNKNOWN      = "unknown"


class QueryComplexity(Enum):
    """degree of complexity of the question — helps determine context budget"""
    LOW    = "low"     # سؤال بسيط  → context صغير
    MEDIUM = "medium"  # سؤال متوسط → context متوسط
    HIGH   = "high"    # سؤال معقد  → context كبير


class RetrievalMethod(Enum):
    """method of retrieval used"""
    VECTOR   = "vector"
    KEYWORD  = "keyword"
    METADATA = "metadata"
    HYBRID   = "hybrid"


class SourceQuality(Enum):
    """quality of the source — affects the ranking factor"""
    HIGH   = 3
    MEDIUM = 2
    LOW    = 1
    UNKNOWN = 0


# ─────────────────────────────────────────────────────────────────────────────
#  Query Analysis Result
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class QueryAnalysis:
    """
    Result of the full query analysis.
    Generated by QueryAnalyzer and used in all stages of the pipeline.
    """
    original_query:  str
    normalized:      str                        # النص بعد التنظيف
    intent:          QueryIntent   = QueryIntent.UNKNOWN
    complexity:      QueryComplexity = QueryComplexity.MEDIUM
    keywords:        List[str]     = field(default_factory=list)
    entities:        List[str]     = field(default_factory=list)   # أسماء / مصطلحات
    is_arabic:       bool          = False
    language:        str           = "en"
    question_type:   str           = ""        # "wh-question", "yes/no", "open"
    context_budget:  int           = 2000      # عدد الأحرف / الـ tokens المقترح
    timestamp:       float         = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "original_query": self.original_query,
            "normalized":     self.normalized,
            "intent":         self.intent.value,
            "complexity":     self.complexity.value,
            "keywords":       self.keywords,
            "entities":       self.entities,
            "is_arabic":      self.is_arabic,
            "language":       self.language,
            "question_type":  self.question_type,
            "context_budget": self.context_budget,
        }


# ─────────────────────────────────────────────────────────────────────────────
#  Chunk Wrapper (adapts any chunk object into unified interface)
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class ScoredChunk:
    """
    Wrapper for any chunk-like object (DocumentChunk, EnhancedChunk, etc.)
    Includes all scoring and metadata needed for ranking and filtering.
    """
    chunk:              Any                       # الكائن الأصلي (DocumentChunk / EnhancedChunk / أي شيء)
    vector_score:       float  = 0.0             # درجة التشابه الدلالي
    keyword_score:      float  = 0.0             # درجة تطابق الكلمات المفتاحية
    metadata_score:     float  = 0.0             # درجة تطابق البيانات الوصفية
    source_quality:     SourceQuality = SourceQuality.UNKNOWN
    recency_score:      float  = 0.0             # حداثة المعلومات (0-1)
    composite_score:    float  = 0.0             # الدرجة الكلية المحسوبة
    retrieval_method:   RetrievalMethod = RetrievalMethod.VECTOR
    retrieval_rank:     int    = 0               # الترتيب الأصلي قبل إعادة الترتيب
    _content_hash:      str    = field(default="", init=False, repr=False)

    def __post_init__(self):
        self._content_hash = hashlib.sha256(
            " ".join(self.text.lower().split()).encode()
        ).hexdigest()

    # ── Unified property access (works for any chunk type) ────────────────

    @property
    def text(self) -> str:
        return getattr(self.chunk, "text", "") or getattr(self.chunk, "page_content", "")

    @property
    def doc_id(self) -> str:
        return getattr(self.chunk, "doc_id", "") or getattr(self.chunk, "id", "")

    @property
    def metadata(self) -> Dict[str, Any]:
        return getattr(self.chunk, "metadata", {}) or {}

    @property
    def source(self) -> str:
        return (
            self.metadata.get("source")
            or getattr(self.chunk, "source", "")
            or self.doc_id
        )

    @property
    def content_hash(self) -> str:
        return self._content_hash

    @property
    def char_count(self) -> int:
        return len(self.text)

    # Legacy compatibility: allow (chunk, score) tuple unpacking
    def __iter__(self):
        yield self.chunk
        yield self.composite_score

    def to_dict(self) -> Dict[str, Any]:
        return {
            "doc_id":          self.doc_id,
            "text_preview":    self.text[:120],
            "vector_score":    round(self.vector_score, 4),
            "keyword_score":   round(self.keyword_score, 4),
            "composite_score": round(self.composite_score, 4),
            "source_quality":  self.source_quality.name,
            "retrieval_method":self.retrieval_method.value,
        }


# ─────────────────────────────────────────────────────────────────────────────
#  Context Output
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class ContextResult:
    """
    Final context output after retrieval, filtering, and ranking.
    This is what gets fed into the LLM as context.
    """
    context:             str                     # السياق الجاهز للـ LLM
    query_analysis:      QueryAnalysis           # تحليل الاستعلام
    chunks_used:         List[ScoredChunk]       # الـ chunks المُدرجة فعلياً
    total_retrieved:     int    = 0              # عدد الـ chunks المُسترجعة قبل الفلترة
    total_after_filter:  int    = 0              # بعد الفلترة
    total_after_rank:    int    = 0              # بعد الترتيب
    total_included:      int    = 0              # المُدرجة في السياق
    context_length:      int    = 0              # طول السياق بالأحرف
    pipeline_ms:         float  = 0.0           # وقت المعالجة بالـ ms
    guard_passed:        bool   = True           # هل اجتاز Context Guard
    guard_warnings:      List[str] = field(default_factory=list)
    metadata:            Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        self.context_length  = len(self.context)
        self.total_included  = len(self.chunks_used)

    def get_stats(self) -> Dict[str, Any]:
        return {
            "pipeline_ms":        round(self.pipeline_ms, 2),
            "total_retrieved":    self.total_retrieved,
            "total_after_filter": self.total_after_filter,
            "total_after_rank":   self.total_after_rank,
            "total_included":     self.total_included,
            "context_length":     self.context_length,
            "guard_passed":       self.guard_passed,
            "guard_warnings":     self.guard_warnings,
            "query_intent":       self.query_analysis.intent.value,
            "query_complexity":   self.query_analysis.complexity.value,
            "context_budget":     self.query_analysis.context_budget,
        }


# ─────────────────────────────────────────────────────────────────────────────
#  Conversation Turn (Multi-turn support)
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class ConversationTurn:
    """Represents a single turn in a conversation (user query + system answer)."""
    turn_id:       int
    query:         str
    answer:        str                = ""
    context_used:  str                = ""
    analysis:      Optional[QueryAnalysis] = None
    timestamp:     float              = field(default_factory=time.time)


@dataclass
class ConversationHistory:
    """
    Complete conversation history — supports multi-turn RAG.
    Used to enrich subsequent queries with context from the conversation.
    """
    session_id:  str
    turns:       List[ConversationTurn] = field(default_factory=list)
    max_turns:   int = 10

    def add_turn(
        self,
        query:    str,
        answer:   str        = "",
        context:  str        = "",
        analysis: Optional[QueryAnalysis] = None,
    ) -> ConversationTurn:
        turn = ConversationTurn(
            turn_id      = len(self.turns),
            query        = query,
            answer       = answer,
            context_used = context,
            analysis     = analysis,
        )
        self.turns.append(turn)
        # Keep only the last max_turns
        if len(self.turns) > self.max_turns:
            self.turns = self.turns[-self.max_turns:]
        return turn

    def get_recent_context(self, n: int = 3) -> str:
        """Extract the most recent n questions and answers as additional context."""
        recent = self.turns[-n:]
        parts = []
        for t in recent:
            if t.query and t.answer:
                parts.append(f"Q: {t.query}\nA: {t.answer}")
        return "\n\n".join(parts)

    def get_enriched_query(self, current_query: str, n: int = 2) -> str:
        """
        Enrich the current query with context from the previous conversation.
        """
        if not self.turns:
            return current_query
        recent_ctx = self.get_recent_context(n)
        if not recent_ctx:
            return current_query
        return f"[Previous conversation:\n{recent_ctx}]\n\nCurrent question: {current_query}"
